// Every piece of UI text, in Spanish (CLAUDE.md §12).
export const copy = {
  /** Labels of the base muscle groups (shared/muscleGroups.ts keys). */
  muscleGroups: {
    chest: 'Pecho',
    back: 'Espalda',
    biceps: 'Bíceps',
    triceps: 'Tríceps',
    shoulders: 'Hombro',
    legs: 'Pierna',
    glutes: 'Glúteo',
    calves: 'Pantorrilla',
    core: 'Core',
    cardio: 'Cardio',
  },
  picker: {
    title: '¿Qué toca hoy?',
    subtitle: 'Primero lo que más tiempo lleva sin entrenar. El orden en que tocas es el orden de la sesión.',
    never: 'sin registro',
    other: 'Otro…',
    otherPlaceholder: 'Escribe el grupo',
    start: 'Empezar',
  },
  /** Screen 2 of the per-exercise flow: the weight selector. */
  selector: {
    lastTime: (day: string) => `La última vez · ${day}`,
    unit: { bar: 'kg por lado', stack: 'kg', rack_per_dumbbell: 'kg c/u', rack_total: 'kg' },
    up: (diff: string, floor: number) => `+${diff} kg · apunta a ${floor} o más`,
    same: (day: string, target: string | null) => `igual que el ${day}${target ? ` · apunta a ${target}` : ''}`,
    down: (diff: string, day: string) => `−${diff} kg que el ${day}`,
    loadTheBar: 'carga la barra',
    addPlateBothSides: (kg: string) => `Cargar disco de ${kg} kg por lado`,
    suggested: 'sugerido',
    backToSuggested: (kg: string) => `↺ sugerido ${kg}`,
    start: (kg: string, unit: string) => `Empezar con ${kg} ${unit}`,
    addPlate: (kg: string) => `Agregar disco de ${kg} kg`,
    removePlate: (kg: string) => `Quitar disco de ${kg} kg`,
    choose: (kg: string) => `${kg} kg`,
  },
  /** The per-exercise flow (design/flujo-ejercicio.html): the list, training and the reps. */
  flow: {
    lastTime: (day: string) => `tu última vez, ${day}`,
    noHistory: 'sin registro',
    otherPlaceholder: '¿Otro? Dímelo',
    inProgress: 'en curso',
    aimBefore: 'Apunta a ',
    aimAfter: ' por serie',
    lastWith: (load: string) => `La última vez, con ${load}`,
    changeWeight: 'cambiar peso',
    done: 'Terminé',
    withLoad: (load: string) => `con ${load}`,
    howMany: '¿Cuántas hiciste?',
    set: (n: number) => `Serie ${n}`,
    before: (reps: number) => `antes ${reps}`,
    more: 'Una rep más',
    fewer: 'Una rep menos',
    addSet: '+ Agregar serie',
    swipeHint: 'Desliza una serie a la izquierda para quitarla.',
    removeSet: 'Quitar',
    sayIt: 'O dilo como siempre',
    sayPlaceholder: '3 de 8 y una de 7',
    save: 'Guardar',
    unclear: 'No lo entendí. Prueba con “3 de 8 y una de 7”, o ajusta las series con − y +.',
    offline: 'Sin señal para entender eso: ajusta las series con − y +.',
  },
  /** History (6 oct 2026): past sessions, one session, one exercise over time. */
  history: {
    back: 'Volver',
    yourSessions: 'Tus sesiones',
    groupSessions: (group: string) => `${group} · tus sesiones`,
    empty: 'Todavía no hay sesiones terminadas.',
    exerciseEmpty: 'Todavía no hay registros de este ejercicio.',
    firstTime: 'primera vez',
  },
  session: {
    load: 'Peso',
    sets: 'Series',
    before: 'antes',
    perSideShort: 'por lado',
    backTo: (reps: number) => `vuelves a ${reps}`,
    last: 'Última:',
    noLast: 'Sin registro',
    mic: 'Dictar',
    send: 'Enviar',
    today: 'Hoy',
    vs: 'vs.',
    firstTime: 'primera vez',
    pending: 'pendiente',
    // Screen 5
    otherPlaceholder: 'U otra cosa, dímelo',
    lastLoad: 'última',
    noLastLoad: 'sin registro',
    // Replies that aren't an entry
    unclear: 'No te entendí. Dime el ejercicio, el peso y las series.',
    noSignal: 'Sin señal: lo que anotes se guarda y se anota cuando vuelva.',
    offline: 'Sin señal: lo guardé y lo anoto cuando vuelva.',
    unclearRetry: (said: string) => `No entendí “${said}”. Dímelo de nuevo.`,
    // M7: voice and photo (design/photo.html)
    undo: 'Deshacer',
    delete: 'Borrar',
    camera: 'Foto de la máquina',
    removePhoto: 'Quitar la foto',
    photoHint: 'Dile peso y series; la máquina la reconoce de la foto.',
    listening: 'Escuchando… toca el micrófono para parar',
    stopListening: 'Dejar de escuchar',
    micPermission: 'Para dictar, activa el micrófono y el reconocimiento de voz para unamas en Ajustes.',
    micUnavailable: 'El dictado no está disponible en este teléfono.',
    cameraPermission: 'Para la foto, activa la cámara para unamas en Ajustes.',
    // Screen 6
    holdToEnd: 'Mantén para terminar',
    stopLabel: 'Terminar la sesión',
    stopHint: 'Mantén presionado un segundo y medio',
    ended: 'Sesión terminada',
    // Screen 7
    nextTime: 'La próxima vez',
    close: 'Cerrar',
    // Screen 1: a doubt from a session already stopped
    fromSession: (day: string, groups: string) => `De tu sesión del ${day.toLowerCase()} · ${groups}`,
    notNow: 'Ahora no',
  },
} as const;
