import type { ExerciseKind, LoadBasis } from '@/domain/types';

import type { Db } from './db';

/** Shape of dev/seed.json (generated by dev/make_seed.py). */
export interface Seed {
  exercises: {
    id: string;
    canonical_name: string;
    aliases: string[];
    muscle_groups: string[];
    kind: ExerciseKind;
    rep_floor: number;
    rep_top: number;
    step_kg: number;
    load_basis: LoadBasis;
  }[];
  sessions: {
    id: string;
    date: string;
    muscle_groups: string[];
    duration_min: number | null;
    avg_bpm: number | null;
  }[];
  entries: {
    id: string;
    session_id: string;
    exercise_id: string;
    load_kg: number | null;
    reps: number[];
    raw_text: string;
  }[];
}

/** The seed has dates only: sessions start at 18:00 local time and last this long when unknown. */
const SEED_START_HOUR = 18;
const SEED_DEFAULT_DURATION_MIN = 60;

/** Loads the seed into an empty database. Does nothing if there is any exercise already. */
export async function loadSeed(db: Db, seed: Seed): Promise<void> {
  const row = await db.getFirstAsync<{ n: number }>('SELECT count(*) AS n FROM exercise', []);
  if (row && row.n > 0) return;

  const sessionStart = new Map<string, Date>();
  const sessionMinutes = new Map<string, number>();
  for (const s of seed.sessions) {
    const [y, m, d] = s.date.split('-').map(Number);
    sessionStart.set(s.id, new Date(y, m - 1, d, SEED_START_HOUR));
    sessionMinutes.set(s.id, s.duration_min ?? SEED_DEFAULT_DURATION_MIN);
  }
  // An exercise exists since the first session it shows up in.
  const firstSeen = new Map<string, Date>();
  for (const e of seed.entries) {
    const start = sessionStart.get(e.session_id)!;
    const seen = firstSeen.get(e.exercise_id);
    if (!seen || start < seen) firstSeen.set(e.exercise_id, start);
  }

  await db.withTransactionAsync(async () => {
    for (const x of seed.exercises) {
      await db.runAsync(
        `INSERT INTO exercise (id, canonical_name, aliases, muscle_groups, kind, rep_floor, rep_top, step_kg, load_basis, created_at)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [
          x.id,
          x.canonical_name,
          JSON.stringify(x.aliases),
          JSON.stringify(x.muscle_groups),
          x.kind,
          x.rep_floor,
          x.rep_top,
          x.step_kg,
          x.load_basis,
          (firstSeen.get(x.id) ?? sessionStart.get(seed.sessions[0].id)!).toISOString(),
        ],
      );
    }
    for (const s of seed.sessions) {
      const start = sessionStart.get(s.id)!;
      const end = addMinutes(start, sessionMinutes.get(s.id)!);
      await db.runAsync(
        'INSERT INTO session (id, muscle_groups, started_at, ended_at, avg_bpm) VALUES (?, ?, ?, ?, ?)',
        [s.id, JSON.stringify(s.muscle_groups), start.toISOString(), end.toISOString(), s.avg_bpm],
      );
    }
    // Entries spread evenly across their session.
    for (const s of seed.sessions) {
      const entries = seed.entries.filter((e) => e.session_id === s.id);
      const gap = sessionMinutes.get(s.id)! / entries.length;
      for (const [i, e] of entries.entries()) {
        await db.runAsync(
          `INSERT INTO entry (id, session_id, exercise_id, load_kg, reps, raw_text, status, created_at)
           VALUES (?, ?, ?, ?, ?, ?, 'ok', ?)`,
          [
            e.id,
            e.session_id,
            e.exercise_id,
            e.load_kg,
            JSON.stringify(e.reps),
            e.raw_text,
            addMinutes(sessionStart.get(s.id)!, gap * i).toISOString(),
          ],
        );
      }
    }
  });
}

function addMinutes(d: Date, minutes: number): Date {
  return new Date(d.getTime() + minutes * 60_000);
}
